_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.9.13
        t:
            "1":
                - 1
                - 30
                - 55
            "2":
                - 1
                - 30
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.13
            "5": 0.19.10
            "8":
                - 5
            "12": 0.19.10
            "13": darwin-x86_64
ONSstep:
    value: 100
alpha:
    value: 3
batch_size:
    value: 250
device:
    value: null
dim_manifold:
    value: 4
dt:
    value: 0.002
g:
    value: 5
gradient_flossing_period:
    value: 4000
iext:
    value: 0
lr_main:
    value: 0.004
lr_pf:
    value: 0.01
mu_Win:
    value: 0
mu_v1:
    value: 0
n_epochs:
    value: 50
n_preflossing_epochs:
    value: 30
n_samples_streaming:
    value: 16
nb_classes:
    value: 2
nb_hidden:
    value: 128
nb_inputs:
    value: 128
nb_outputs:
    value: 2
nb_samples:
    value: 1000
nb_spikes:
    value: 1
nb_time_steps:
    value: 100
nle:
    value: 20
output_dir:
    value: /Users/user/Desktop/lyapunov_snn_sg/results
prediction_offset:
    value: 80
prefloss:
    value: true
prefloss_batch_size:
    value: 1
randmanseed:
    value: 2
seed_init:
    value: 1
seed_train:
    value: 1
seedONS:
    value: 1
sigma_Win:
    value: 5
sigma_v1:
    value: 5
step_frac:
    value: 0.5
tau_mem:
    value: 0.02
tau_readout:
    value: 100
tau_syn:
    value: 0.01
time_step:
    value: 1000
trainable_dt:
    value: false
trainable_tau:
    value: false
wandb_key:
    value: ffcb223d1cd1485839a2367cb49d82485cd8ffb0
